In [ ]:
##Question 1
#begin
list=[i for i in range(2000,3201) if i%7 == 0 and i%5!= 0]
print(list)
#end

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [ ]:
##Question2
#begin
N =5
# 5!=1*2*3*4*5
def factoriel(n):
  liste =[1,2]
  resultat = 2
  for i in range(3,n+1):
   resultat = resultat * i
   liste.append(resultat)
  return resultat,liste
resultat = factoriel(n=N)
print (resultat)
#end


(120, [1, 2, 6, 24, 120])


In [ ]:
##Question3
#begin
n=8
dict ={}
for i in range(1,n+1):
  dict[i] = i*i
print(dict)
#end


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [ ]:
##Question4
#begin
def missing_char(str,n):
  return str.replace(str[n],'')
print(missing_char('kitten',1))
print(missing_char('kitten',0))
print(missing_char('kitten',4))
#end

ktten
itten
kittn


In [ ]:
##Question5
#begin
import numpy as np
x = np.arange(6).reshape(3,2)
print('Original array elements:')
print(x)
print('Array to list:')
print(x.tolist())
#end

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [ ]:
##Question6
#begin
import numpy as np
X1=[0,1,2]
X2=[2,1,0]
X1=np.array(X1)
X2=np.array(X2)
print('Original array1:')
print(X1)
print('Original array2:')
print(X2)
print('Covariance matrix of the said arrays:')
print(np.cov(X1,X2))
#end

Original array1:
[0 1 2]
Original array2:
[2 1 0]
Covariance matrix of the said arrays:
[[ 1. -1.]
 [-1.  1.]]


In [ ]:
##Question7
#begin
import math
C = 50
H = 30
value =[]
result =[]
Items =[i for i in input().split(",")]
for D in Items:
  value.append(str(int(round(math.sqrt((2*C*float(D))/H)))))

print(','.join(value)) 
#end




100,150,180
18,22,24
